### PR TITLE
update GitHub actions

### PR DESCRIPTION
**Pull request by smyrman**
commit e313d686090d4b8bf381881d4d94f7b9c884cdaf (HEAD -> actions, origin/actions)
Author: Sindre Myren <sindre@clarify.io>
Date:   Wed Oct 12 14:28:23 2022 +0200

    .github/workflows/go.yml: update actions

commit 292b666ee016cdee6839a2f2238e1c6d3ec99edc
Author: Sindre Myren <sindre@clarify.io>
Date:   Wed Oct 12 14:37:23 2022 +0200

    lint: fix linter issues

### CODE REVIEW

**Comment by sarzhann** [comment]
I see here only one commit from your list `lint: fix linter issues`

**Comment by smyrman** [comment]
Seams that it was lost while rebasing; will fix.

**Comment by smyrman** [comment]
done

**Review by sarzhann — APPROVED** [review]
👍

**Pull request merged**
